### ISSUE TITLE
global.getTestDB() needs to be moved

### ISSUE THREAD

**Issue by ZacheryPD** [jchristi/syndicat#3]
global.getTestDB is currently defined for each test.  This needs to be moved into an index.js file and removed from each test.

**Comment by jchristi** [comment]
If you put "closes !1" in your commit message, it will automatically close the github issue. Can also put in the PR description to link the two items. See [Closing Issues via Commit Messages](https://help.github.com/articles/closing-issues-via-commit-messages/)
